openapi: 3.1.0
info:
  title: Landscape API
  version: 0.0.1
servers:
  - url: 'https://{landscape_root_url}'
    variables:
      landscape_root_url:
        default: landscape.canonical.com
security:
  - bearerAuth: []
paths:
  '/api/scripts/{script_id}':
    parameters:
      - $ref: '#/components/parameters/ScriptIdPathParam'
    get:
      operationId: get_script
      description: Get a specific script.
      responses:
        '200':
          description: The found script and its state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Script'
        '404':
          $ref: '#/components/responses/ScriptNotFound'
  '/api/scripts/{script_id}:archive':
    parameters:
      - $ref: '#/components/parameters/ScriptIdPathParam'
    post:
      operationId: archive_script
      summary: Archive a script.
      description: Archive a script and any associated script profiles. Redacted scripts cannot be archived.
      responses:
        '204':
          description: Script archived successfully.
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/ScriptNotFound'
  '/api/scripts/{script_id}:redact':
    parameters:
      - $ref: '#/components/parameters/ScriptIdPathParam'
    post:
      operationId: redact_script
      summary: Redact a script.
      description: 'Redact a script, archive profiles, delete attachments, and redact script versions.'
      responses:
        '204':
          description: Script redacted successfully.
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/ScriptNotFound'
  /api/:
    parameters:
      - $ref: '#/components/parameters/LegacyVersionParam'
      - $ref: '#/components/parameters/LegacyActionParam'
    post:
      tags:
        - Legacy Actions
      operationId: invoke_legacy_action
      summary: Invoke a legacy action.
      description: |
        Calls Landscape legacy API endpoints. Provide the desired action name in the `action` query parameter and include the corresponding parameters in the query string.
      responses:
        '200':
          $ref: '#/components/responses/LegacyActionResponse'
        '204':
          description: The legacy action completed successfully without a response body.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  /api/login:
    post:
      tags:
        - Authentication
      operationId: login_with_password
      summary: Authenticate with email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Authentication succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      security: []
  /api/login/access-key:
    post:
      tags:
        - Authentication
      operationId: login_with_access_key
      summary: Authenticate with access and secret key.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessKeyLoginRequest'
      responses:
        '200':
          description: Authentication succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      security: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    ScriptIdPathParam:
      name: script_id
      in: path
      required: true
      schema:
        type: integer
      description: The ID of the script.
    LegacyVersionParam:
      name: version
      in: query
      required: true
      schema:
        type: string
        const: '2011-08-01'
      description: The legacy API version. Landscape currently expects the fixed value `2011-08-01`.
    LegacyActionParam:
      name: action
      in: query
      required: true
      schema:
        type: string
        minLength: 1
      description: The legacy API action name to invoke.
  schemas:
    Script:
      type: object
      properties:
        id:
          type: integer
          x-oapi-codegen-extra-tags:
            tfsdk: id
        title:
          type: string
          x-oapi-codegen-extra-tags:
            tfsdk: title
        version:
          type: integer
          x-oapi-codegen-extra-tags:
            tfsdk: version
        created_at:
          type: string
          x-oapi-codegen-extra-tags:
            tfsdk: created_at
        created_by:
          type: string
          x-oapi-codegen-extra-tags:
            tfsdk: created_by
        last_edited_by:
          type: string
          x-oapi-codegen-extra-tags:
            tfsdk: last_edited_by
        script_profiles:
          type: array
          x-oapi-codegen-extra-tags:
            tfsdk: script_profiles
        status:
          type: string
          x-oapi-codegen-extra-tags:
            tfsdk: status
        attachments:
          type: array
          x-oapi-codegen-extra-tags:
            tfsdk: attachments
        code:
          type: string
          x-oapi-codegen-extra-tags:
            tfsdk: code
        interpreter:
          type: string
          x-oapi-codegen-extra-tags:
            tfsdk: interpreter
        access_group:
          type: string
          x-oapi-codegen-extra-tags:
            tfsdk: access_group
        time_limit:
          type: integer
          x-oapi-codegen-extra-tags:
            tfsdk: time_limit
        username:
          type: string
          x-oapi-codegen-extra-tags:
            tfsdk: username
        is_redactable:
          type: boolean
          x-oapi-codegen-extra-tags:
            tfsdk: is_redactable
        is_editable:
          type: boolean
          x-oapi-codegen-extra-tags:
            tfsdk: is_editable
        is_executable:
          type: boolean
          x-oapi-codegen-extra-tags:
            tfsdk: is_executable
      required:
        - id
        - title
    CreateScriptAction:
      type: object
      additionalProperties: false
      properties:
        title:
          type: string
          description: Title for the new script.
          x-oapi-codegen-extra-tags:
            tfsdk: title
        time_limit:
          type: integer
          description: Maximum number of seconds the script may execute.
          x-oapi-codegen-extra-tags:
            tfsdk: time_limit
        code:
          type: string
          description: Script contents encoded as base64 UTF-8.
          x-oapi-codegen-extra-tags:
            tfsdk: code
        username:
          type: string
          description: System user under which the script runs.
          x-oapi-codegen-extra-tags:
            tfsdk: username
        access_group:
          type: string
          description: Access group to assign the script to.
          x-oapi-codegen-extra-tags:
            tfsdk: access_group
      required:
        - title
        - code
    EditScriptAction:
      type: object
      additionalProperties: false
      properties:
        script_id:
          type: integer
          description: Identifier of the script being edited.
          x-oapi-codegen-extra-tags:
            tfsdk: script_id
        title:
          type: string
          description: Updated script title.
          x-oapi-codegen-extra-tags:
            tfsdk: title
        time_limit:
          type: integer
          description: Updated execution time limit in seconds.
          x-oapi-codegen-extra-tags:
            tfsdk: time_limit
        code:
          type: string
          description: Updated script contents encoded as base64 UTF-8.
          x-oapi-codegen-extra-tags:
            tfsdk: code
        username:
          type: string
          description: Updated system user to execute the script.
          x-oapi-codegen-extra-tags:
            tfsdk: username
      required:
        - script_id
    CopyScriptAction:
      type: object
      additionalProperties: false
      properties:
        script_id:
          type: integer
          description: ID of the script to copy.
          x-oapi-codegen-extra-tags:
            tfsdk: script_id
        destination_title:
          type: string
          description: Title for the cloned script.
          x-oapi-codegen-extra-tags:
            tfsdk: destination_title
        access_group:
          type: string
          description: Access group for the cloned script.
          x-oapi-codegen-extra-tags:
            tfsdk: access_group
      required:
        - script_id
        - destination_title
    RemoveScriptAction:
      type: object
      additionalProperties: false
      properties:
        script_id:
          type: integer
          description: Identifier of the script to remove.
          x-oapi-codegen-extra-tags:
            tfsdk: script_id
      required:
        - script_id
    CreateScriptAttachmentAction:
      type: object
      additionalProperties: false
      properties:
        script_id:
          type: integer
          description: Identifier of the script receiving the attachment.
          x-oapi-codegen-extra-tags:
            tfsdk: script_id
        file:
          type: string
          description: Attachment payload in the format `<filename>$$<base64 contents>`.
          x-oapi-codegen-extra-tags:
            tfsdk: file
      required:
        - script_id
        - file
    RemoveScriptAttachmentAction:
      type: object
      additionalProperties: false
      properties:
        script_id:
          type: integer
          description: Identifier of the script owning the attachment.
          x-oapi-codegen-extra-tags:
            tfsdk: script_id
        filename:
          type: string
          description: Name of the attachment to remove.
          x-oapi-codegen-extra-tags:
            tfsdk: filename
      required:
        - script_id
        - filename
    LegacyActionRequest:
      description: Legacy actions accept their parameters via query string and do not define a request body schema.
      type: object
    LegacyActionResult:
      oneOf:
        - $ref: '#/components/schemas/Script'
        - type: object
          additionalProperties: false
          properties:
            filename:
              type: string
              description: Name of the attachment that was created.
              x-oapi-codegen-extra-tags:
                tfsdk: filename
          required:
            - filename
    LoginRequest:
      type: object
      additionalProperties: false
      properties:
        email:
          type: string
          format: email
          description: Email address used to authenticate with Landscape Server.
          x-oapi-codegen-extra-tags:
            tfsdk: email
        password:
          type: string
          format: password
          description: Password associated with the provided email.
          x-oapi-codegen-extra-tags:
            tfsdk: password
        account:
          type: string
          nullable: true
          description: The account to login into (optional).
          x-oapi-codegen-extra-tags:
            tfsdk: account
      required:
        - email
        - password
    AccessKeyLoginRequest:
      type: object
      additionalProperties: false
      properties:
        access_key:
          type: string
          description: Access key issued for API authentication.
          x-oapi-codegen-extra-tags:
            tfsdk: access_key
        secret_key:
          type: string
          description: Secret key paired with the access key.
          x-oapi-codegen-extra-tags:
            tfsdk: secret_key
      required:
        - access_key
        - secret_key
    LoginAccount:
      type: object
      additionalProperties: false
      properties:
        default:
          type: boolean
          description: Indicates whether this is the default account.
          x-oapi-codegen-extra-tags:
            tfsdk: default
        name:
          type: string
          description: Internal account identifier.
          x-oapi-codegen-extra-tags:
            tfsdk: name
        title:
          type: string
          description: Display name for the account.
          x-oapi-codegen-extra-tags:
            tfsdk: title
        classic_dashboard_url:
          type: string
          format: uri
          description: URL of the classic dashboard for the account.
          x-oapi-codegen-extra-tags:
            tfsdk: classic_dashboard_url
        subdomain:
          type: string
          nullable: true
          description: Optional subdomain assigned to the account.
          x-oapi-codegen-extra-tags:
            tfsdk: subdomain
      required:
        - default
        - name
        - title
    LoginResponse:
      type: object
      additionalProperties: true
      properties:
        accounts:
          type: array
          description: Accounts available to the authenticated user.
          x-oapi-codegen-extra-tags:
            tfsdk: accounts
          items:
            $ref: '#/components/schemas/LoginAccount'
        current_account:
          type: string
          description: Identifier of the account in current use.
          x-oapi-codegen-extra-tags:
            tfsdk: current_account
        email:
          type: string
          format: email
          description: Email address of the authenticated user.
          x-oapi-codegen-extra-tags:
            tfsdk: email
        name:
          type: string
          description: Display name of the authenticated user.
          x-oapi-codegen-extra-tags:
            tfsdk: name
        self_hosted:
          type: boolean
          description: Indicates whether the Landscape deployment is self hosted.
          x-oapi-codegen-extra-tags:
            tfsdk: self_hosted
        token:
          type: string
          description: JWT used to authorize subsequent API requests.
          x-oapi-codegen-extra-tags:
            tfsdk: token
      required:
        - accounts
        - current_account
        - email
        - token
    Error:
      type: object
      properties:
        code:
          type: integer
          x-oapi-codegen-extra-tags:
            tfsdk: code
        message:
          type: string
          x-oapi-codegen-extra-tags:
            tfsdk: message
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ScriptNotFound:
      description: The specified script does not exist.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    LegacyActionResponse:
      description: Result returned by a legacy action.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LegacyActionResult'
