openapi: 3.1.0
info:
  title: Landscape API
  version: "0.0.1"

servers:
  - url: https://{landscape_root_url}
    variables:
      landscape_root_url:
        default: landscape.canonical.com

security:
  - bearerAuth: []

paths:
  "/api/scripts/{script_id}":
    parameters:
      - $ref: "#/components/parameters/ScriptIdPathParam"
    get:
      operationId: get_script
      description: Get a specific script.
      responses:
        "200":
          $ref: "./components/responses/script.yaml#/GetScriptResponse"
        "404":
          $ref: "./components/responses/error.yaml#/ScriptNotFound"
  "/api/scripts/{script_id}:archive":
    parameters:
      - $ref: "#/components/parameters/ScriptIdPathParam"
    post:
      operationId: archive_script
      summary: Archive a script.
      description: Archive a script and any associated script profiles. Redacted scripts cannot be archived.
      responses:
        "204":
          description: Script archived successfully.
        "401":
          $ref: "./components/responses/error.yaml#/Unauthorized"
        "404":
          $ref: "./components/responses/error.yaml#/ScriptNotFound"
  "/api/scripts/{script_id}:redact":
    parameters:
      - $ref: "#/components/parameters/ScriptIdPathParam"
    post:
      operationId: redact_script
      summary: Redact a script.
      description: Redact a script, archive profiles, delete attachments, and redact script versions.
      responses:
        "204":
          description: Script redacted successfully.
        "401":
          $ref: "./components/responses/error.yaml#/Unauthorized"
        "404":
          $ref: "./components/responses/error.yaml#/ScriptNotFound"
  "/api/":
    $ref: "./components/paths/actions.yaml#/paths/~1api~1"
  "/api/login":
    $ref: "./components/paths/auth.yaml#/paths/~1api~1login"
  "/api/login/access-key":
    $ref: "./components/paths/auth.yaml#/paths/~1api~1login~1access-key"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    ScriptIdPathParam:
      $ref: "./components/parameters/script.yaml#/ScriptIdPathParam"
    LegacyVersionParam:
      $ref: "./components/parameters/legacy.yaml#/LegacyVersionParam"
    LegacyActionParam:
      $ref: "./components/parameters/legacy.yaml#/LegacyActionParam"

  schemas:
    Script:
      $ref: "./components/schemas/script.yaml#/Script"
    ScriptCreator:
      $ref: "./components/schemas/script.yaml#/ScriptCreator"
    ScriptAttachment:
      $ref: "./components/schemas/script.yaml#/ScriptAttachment"
    LegacyScriptAttachment:
      $ref: "./components/schemas/script.yaml#/LegacyScriptAttachment"
    LegacyScriptCreator:
      $ref: "./components/schemas/script.yaml#/LegacyScriptCreator"
    ScriptProfile:
      $ref: "./components/schemas/script.yaml#/ScriptProfile"
    LegacyActionResult:
      $ref: "./components/schemas/legacy.yaml#/LegacyActionResult"
    LoginRequest:
      $ref: "./components/schemas/auth.yaml#/LoginRequest"
    AccessKeyLoginRequest:
      $ref: "./components/schemas/auth.yaml#/AccessKeyLoginRequest"
    LoginAccount:
      $ref: "./components/schemas/auth.yaml#/LoginAccount"
    LoginResponse:
      $ref: "./components/schemas/auth.yaml#/LoginResponse"
    Error:
      $ref: "./components/schemas/error.yaml#/Error"

  responses:
    Unauthorized:
      $ref: "./components/responses/error.yaml#/Unauthorized"
    BadRequest:
      $ref: "./components/responses/error.yaml#/BadRequest"
    NotFound:
      $ref: "./components/responses/error.yaml#/NotFound"
    ScriptNotFound:
      $ref: "./components/responses/error.yaml#/ScriptNotFound"
    LegacyActionResponse:
      $ref: "./components/responses/legacy.yaml#/LegacyActionResponse"
