openapi: 3.1.0
info:
  title: Landscape API
  version: 0.0.1
servers:
  - url: 'https://{landscape_root_url}'
    variables:
      landscape_root_url:
        default: landscape.canonical.com
security:
  - bearerAuth: []
paths:
  '/api/scripts/{scriptId}':
    parameters:
      - $ref: '#/components/parameters/ScriptIdPathParam'
    get:
      operationId: getScript
      description: Get a specific script.
      responses:
        '200':
          description: The found script and its state.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Script'
        '404':
          $ref: '#/components/responses/ScriptNotFound'
  '/api/scripts/{scriptId}:archive':
    parameters:
      - $ref: '#/components/parameters/ScriptIdPathParam'
    post:
      operationId: archiveScript
      summary: Archive a script.
      description: Archive a script and any associated script profiles. Redacted scripts cannot be archived.
      responses:
        '204':
          description: Script archived successfully.
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/ScriptNotFound'
  '/api/scripts/{scriptId}:redact':
    parameters:
      - $ref: '#/components/parameters/ScriptIdPathParam'
    post:
      operationId: redactScript
      summary: Redact a script.
      description: 'Redact a script, archive profiles, delete attachments, and redact script versions.'
      responses:
        '204':
          description: Script redacted successfully.
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/ScriptNotFound'
  /api/:
    parameters:
      - $ref: '#/components/parameters/LegacyVersionParam'
      - $ref: '#/components/parameters/LegacyActionParam'
    post:
      tags:
        - Legacy Actions
      operationId: invokeLegacyAction
      summary: Invoke a legacy action.
      description: |
        Calls Landscape legacy API endpoints. Provide the desired action name in the `action` query parameter and include the corresponding parameters in the query string.
      responses:
        '200':
          $ref: '#/components/responses/LegacyActionResponse'
        '204':
          description: The legacy action completed successfully without a response body.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  /api/login:
    post:
      tags:
        - Authentication
      operationId: loginWithPassword
      summary: Authenticate with email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Authentication succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      security: []
  /api/login/access-key:
    post:
      tags:
        - Authentication
      operationId: loginWithAccessKey
      summary: Authenticate with access and secret key.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessKeyLoginRequest'
      responses:
        '200':
          description: Authentication succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      security: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    ScriptIdPathParam:
      name: scriptId
      in: path
      required: true
      schema:
        type: integer
      description: The ID of the script.
    LegacyVersionParam:
      name: version
      in: query
      required: true
      schema:
        type: string
        const: '2011-08-01'
      description: The legacy API version. Landscape currently expects the fixed value `2011-08-01`.
    LegacyActionParam:
      name: action
      in: query
      required: true
      schema:
        type: string
        minLength: 1
      description: The legacy API action name to invoke.
  schemas:
    Script:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        version:
          type: integer
        createdAt:
          type: string
        createdBy:
          type: string
        lastEditedBy:
          type: string
        scriptProfiles:
          type: array
        status:
          type: string
        attachments:
          type: array
        code:
          type: string
        interpreter:
          type: string
        accessGroup:
          type: string
        timeLimit:
          type: integer
        username:
          type: string
        isRedactable:
          type: boolean
        isEditable:
          type: boolean
        isExecutable:
          type: boolean
      required:
        - id
        - title
    CreateScriptAction:
      type: object
      additionalProperties: false
      properties:
        title:
          type: string
          description: Title for the new script.
        time_limit:
          type: integer
          description: Maximum number of seconds the script may execute.
        code:
          type: string
          description: Script contents encoded as base64 UTF-8.
        username:
          type: string
          description: System user under which the script runs.
        access_group:
          type: string
          description: Access group to assign the script to.
      required:
        - title
        - code
    EditScriptAction:
      type: object
      additionalProperties: false
      properties:
        script_id:
          type: integer
          description: Identifier of the script being edited.
        title:
          type: string
          description: Updated script title.
        time_limit:
          type: integer
          description: Updated execution time limit in seconds.
        code:
          type: string
          description: Updated script contents encoded as base64 UTF-8.
        username:
          type: string
          description: Updated system user to execute the script.
      required:
        - script_id
    CopyScriptAction:
      type: object
      additionalProperties: false
      properties:
        script_id:
          type: integer
          description: ID of the script to copy.
        destination_title:
          type: string
          description: Title for the cloned script.
        access_group:
          type: string
          description: Access group for the cloned script.
      required:
        - script_id
        - destination_title
    RemoveScriptAction:
      type: object
      additionalProperties: false
      properties:
        script_id:
          type: integer
          description: Identifier of the script to remove.
      required:
        - script_id
    CreateScriptAttachmentAction:
      type: object
      additionalProperties: false
      properties:
        script_id:
          type: integer
          description: Identifier of the script receiving the attachment.
        file:
          type: string
          description: Attachment payload in the format `<filename>$$<base64 contents>`.
      required:
        - script_id
        - file
    RemoveScriptAttachmentAction:
      type: object
      additionalProperties: false
      properties:
        script_id:
          type: integer
          description: Identifier of the script owning the attachment.
        filename:
          type: string
          description: Name of the attachment to remove.
      required:
        - script_id
        - filename
    LegacyActionRequest:
      description: Legacy actions accept their parameters via query string and do not define a request body schema.
      type: object
    LegacyActionResult:
      oneOf:
        - $ref: '#/components/schemas/Script'
        - type: object
          additionalProperties: false
          properties:
            filename:
              type: string
              description: Name of the attachment that was created.
          required:
            - filename
    LoginRequest:
      type: object
      additionalProperties: false
      properties:
        email:
          type: string
          format: email
          description: Email address used to authenticate with Landscape.
        password:
          type: string
          format: password
          description: Account password associated with the provided email.
      required:
        - email
        - password
    AccessKeyLoginRequest:
      type: object
      additionalProperties: false
      properties:
        access_key:
          type: string
          description: Access key issued for API authentication.
        secret_key:
          type: string
          description: Secret key paired with the access key.
      required:
        - access_key
        - secret_key
    LoginAccount:
      type: object
      additionalProperties: false
      properties:
        default:
          type: boolean
          description: Indicates whether this is the default account.
        name:
          type: string
          description: Internal account identifier.
        title:
          type: string
          description: Display name for the account.
        classic_dashboard_url:
          type: string
          format: uri
          description: URL of the classic dashboard for the account.
        subdomain:
          type: string
          nullable: true
          description: Optional subdomain assigned to the account.
      required:
        - default
        - name
        - title
    LoginResponse:
      type: object
      additionalProperties: true
      properties:
        accounts:
          type: array
          description: Accounts available to the authenticated user.
          items:
            $ref: '#/components/schemas/LoginAccount'
        current_account:
          type: string
          description: Identifier of the account in current use.
        email:
          type: string
          format: email
          description: Email address of the authenticated user.
        name:
          type: string
          description: Display name of the authenticated user.
        self_hosted:
          type: boolean
          description: Indicates whether the Landscape deployment is self hosted.
        token:
          type: string
          description: JWT used to authorize subsequent API requests.
      required:
        - accounts
        - current_account
        - email
        - token
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ScriptNotFound:
      description: The specified script does not exist.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    LegacyActionResponse:
      description: Result returned by a legacy action.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LegacyActionResult'
